import type { Laboratory } from "./types";

export const LABS: Laboratory[] = [
  {
    slug: "browser",
    code: "LAB-01",
    name: "Browser Lab",
    department: "Department of Browser Behaviour",
    status: "OPERATIONAL",
    tagline: "The engine room. Loud, hot, mostly undocumented.",
    description:
      "Everything between a URL and a lit pixel. We keep a full rendering pipeline mounted on the far wall and run bytes through it until somebody understands what compositing actually means.",
    environment: "engine",
    hazard: "MAIN THREAD MAY BE OCCUPIED",
    accent: "crt",
    topics: [
      "DOM construction",
      "CSSOM",
      "style calculation",
      "layout",
      "paint",
      "compositing",
      "frame budget",
    ],
  },
  {
    slug: "css",
    code: "LAB-02",
    name: "CSS Lab",
    department: "Department of Applied Layout",
    status: "OPERATIONAL",
    tagline: "Where boxes are measured, and then measured again.",
    description:
      "A room full of rulers, coordinate systems and boxes that refuse to be the size you asked for. Home of the institute's stacking context collection, kept behind glass for everyone's safety.",
    environment: "measure",
    hazard: "CONTAINS UNRESOLVED PERCENTAGES",
    accent: "amber",
    topics: [
      "box model",
      "stacking contexts",
      "containing blocks",
      "formatting contexts",
      "intrinsic sizing",
      "specificity",
    ],
  },
  {
    slug: "javascript",
    code: "LAB-03",
    name: "JavaScript Lab",
    department: "Department of Runtime Phenomena",
    status: "OPERATIONAL",
    tagline: "One thread. Infinite opinions.",
    description:
      "Electrical equipment, glowing circuits and a very long queue. We study what the language promises, what the engine actually does, and the gap in between where all the interesting bugs live.",
    environment: "circuit",
    hazard: "SINGLE THREAD. DO NOT BLOCK",
    accent: "signal",
    topics: [
      "event loop",
      "microtasks",
      "closures",
      "coercion",
      "prototypes",
      "memory",
      "garbage collection",
    ],
  },
  {
    slug: "react",
    code: "LAB-04",
    name: "React Lab",
    department: "Department of Reconciliation Studies",
    status: "OPERATIONAL",
    tagline: "Component trees, observed in their natural habitat.",
    description:
      "We attach instruments to a component tree, change one piece of state, and watch how far the tremor travels. Most performance complaints turn out to be a tree shape problem.",
    environment: "tree",
    hazard: "RENDERS MAY OCCUR WITHOUT WARNING",
    accent: "crt",
    topics: [
      "render phase",
      "commit phase",
      "reconciliation",
      "keys",
      "state placement",
      "memoization",
      "batching",
    ],
  },
  {
    slug: "performance",
    code: "LAB-05",
    name: "Performance Lab",
    department: "Department of Wasted Milliseconds",
    status: "OPERATIONAL",
    tagline: "Fast is a budget, not a feeling.",
    description:
      "Oscilloscopes, frame counters and one deliberately terrible website kept alive for research purposes. Visitors are invited to save it. Most cannot.",
    environment: "gauge",
    hazard: "LONG TASKS IN PROGRESS",
    accent: "rust",
    topics: ["LCP", "INP", "CLS", "long tasks", "critical path", "bundle size", "hydration"],
  },
  {
    slug: "networking",
    code: "LAB-06",
    name: "Networking Lab",
    department: "Department of Distance",
    status: "OPERATIONAL",
    tagline: "Every byte travelled further than you think.",
    description:
      "Cables, patch panels and a wall-sized map of round trips. We simulate the physics of distance so nobody has to learn about latency during an incident.",
    environment: "nodes",
    hazard: "PACKETS MAY BE LOST",
    accent: "steel",
    topics: ["DNS", "TCP", "TLS", "HTTP/2", "HTTP/3", "CDN", "caching"],
  },
  {
    slug: "security",
    code: "LAB-07",
    name: "Security Lab",
    department: "Department of Trust Boundaries",
    status: "OPERATIONAL",
    tagline: "Restricted. Bring your own origin.",
    description:
      "Sandboxed and deliberately defanged. We study why the browser security model exists, where its boundaries actually sit, and never how to take somebody else's site apart.",
    environment: "vault",
    hazard: "TRUST BOUNDARY UNDER TEST",
    accent: "rust",
    topics: ["same-origin policy", "XSS", "CSRF", "CORS", "CSP", "cookies"],
  },
  {
    slug: "accessibility",
    code: "LAB-08",
    name: "Accessibility Lab",
    department: "Department of the Invisible DOM",
    status: "OPERATIONAL",
    tagline: "There is a second tree. Most people never look at it.",
    description:
      "Two trees stand side by side: the DOM you wrote and the accessibility tree the browser derived from it. The difference between them is the entire discipline.",
    environment: "twin",
    hazard: "SEMANTICS UNDER OBSERVATION",
    accent: "crt",
    topics: ["accessibility tree", "roles", "names", "focus", "ARIA", "live regions"],
  },
  {
    slug: "architecture",
    code: "LAB-09",
    name: "Architecture Lab",
    department: "Department of Structural Decisions",
    status: "OPERATIONAL",
    tagline: "Every abstraction is a loan with interest.",
    description:
      "Dependency graphs, module boundaries and the long-term cost of a decision made in a hurry on a Friday.",
    environment: "graph",
    hazard: "TRANSITIVE DEPENDENCIES DETECTED",
    accent: "steel",
    topics: ["module boundaries", "dependency graphs", "bundling", "tree shaking", "ESM vs CJS"],
  },
  {
    slug: "algorithms",
    code: "LAB-10",
    name: "Algorithms Lab",
    department: "Department of Complexity",
    status: "OPERATIONAL",
    tagline: "The DOM is a data structure. Act accordingly.",
    description:
      "Where interface problems are re-stated as data structure problems, and then solved with something less exciting than a framework.",
    environment: "graph",
    hazard: "QUADRATIC BEHAVIOUR SUSPECTED",
    accent: "signal",
    topics: ["tree traversal", "diffing", "virtualisation", "scheduling", "data structures"],
  },
];

export const LAB_BY_SLUG = new Map(LABS.map((lab) => [lab.slug, lab]));

export function getLab(slug: string): Laboratory | undefined {
  return LAB_BY_SLUG.get(slug as Laboratory["slug"]);
}
